# Autogenerated from a Treetop grammar. Edits may be lost.


require 'treetop'
require 'whitespace'

module DSL
  module SwimLane
    include Treetop::Runtime

    def root
      @root ||= :diagram
    end

    include DSL::Whitespace

    module Diagram0
      def whitespace1
        elements[0]
      end

      def whitespace2
        elements[2]
      end
    end

    def _nt_diagram
      start_index = index
      if node_cache[:diagram].has_key?(index)
        cached = node_cache[:diagram][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0, s0 = index, []
      r1 = _nt_whitespace
      s0 << r1
      if r1
        if has_terminal?("diagram", false, index)
          r2 = instantiate_node(SyntaxNode,input, index...(index + 7))
          @index += 7
        else
          terminal_parse_failure("diagram")
          r2 = nil
        end
        s0 << r2
        if r2
          r3 = _nt_whitespace
          s0 << r3
        end
      end
      if s0.last
        r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
        r0.extend(Diagram0)
      else
        @index = i0
        r0 = nil
      end

      node_cache[:diagram][start_index] = r0

      r0
    end

  end

  class SwimLaneParser < Treetop::Runtime::CompiledParser
    include SwimLane
  end

end