# Autogenerated from a Treetop grammar. Edits may be lost.


require 'treetop'

module DSL
  module Whitespace
    include Treetop::Runtime

    def root
      @root ||= :whitespace
    end

    def _nt_whitespace
      start_index = index
      if node_cache[:whitespace].has_key?(index)
        cached = node_cache[:whitespace][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0 = index
      s1, i1 = [], index
      loop do
        r2 = _nt_single_whitespace
        if r2
          s1 << r2
        else
          break
        end
      end
      if s1.empty?
        @index = i1
        r1 = nil
      else
        r1 = instantiate_node(SyntaxNode,input, i1...index, s1)
      end
      if r1
        r0 = r1
      else
        r3 = _nt_empty
        if r3
          r0 = r3
        else
          @index = i0
          r0 = nil
        end
      end

      node_cache[:whitespace][start_index] = r0

      r0
    end

    def _nt_single_whitespace
      start_index = index
      if node_cache[:single_whitespace].has_key?(index)
        cached = node_cache[:single_whitespace][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0 = index
      if has_terminal?(" ", false, index)
        r1 = instantiate_node(SyntaxNode,input, index...(index + 1))
        @index += 1
      else
        terminal_parse_failure(" ")
        r1 = nil
      end
      if r1
        r0 = r1
      else
        if has_terminal?("\t", false, index)
          r2 = instantiate_node(SyntaxNode,input, index...(index + 1))
          @index += 1
        else
          terminal_parse_failure("\t")
          r2 = nil
        end
        if r2
          r0 = r2
        else
          if has_terminal?("\n", false, index)
            r3 = instantiate_node(SyntaxNode,input, index...(index + 1))
            @index += 1
          else
            terminal_parse_failure("\n")
            r3 = nil
          end
          if r3
            r0 = r3
          else
            @index = i0
            r0 = nil
          end
        end
      end

      node_cache[:single_whitespace][start_index] = r0

      r0
    end

    def _nt_empty
      start_index = index
      if node_cache[:empty].has_key?(index)
        cached = node_cache[:empty][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      if has_terminal?("", false, index)
        r0 = instantiate_node(SyntaxNode,input, index...(index + 0))
        @index += 0
      else
        terminal_parse_failure("")
        r0 = nil
      end

      node_cache[:empty][start_index] = r0

      r0
    end

  end

  class WhitespaceParser < Treetop::Runtime::CompiledParser
    include Whitespace
  end

end